### ISSUE TITLE
Gnotifier needs verification on Firefox 45.0.2

### ISSUE THREAD

**Issue by afettouhi** [mkiol/GNotifier#101]
I've been trying to install gnotifier 1.9.6 and 1.9.7pre1. Both fail on Firefox 45.0.2 on Arch Linux because the extension isn't verified.

**Comment by mkiol** [comment]
Did you try the package from [AMO](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/)? In general, only XPIs form AMO are signed and verified by Mozilla.

**Comment by afettouhi** [comment]
Yep tried it and it worked, many thanks.
