### ISSUE TITLE
[FF+TB] no app icons in notifications (Win 10)

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#104]
I upgraded to Windows 10 today.
While notifications used to don't work at all on Windows 8.1, they now work... that's great!!

But I can't get them to show the application icons. `default`, `firefox` or `thunderbird`... all the same.

**Comment by mkiol** [comment]
> While notifications used to don't work at all on Windows 8.1

I tested it couple of times and didn't have any problems on W8.1. What was the exact configuration of your environment? TB, FF versions, addon version, win patches, etc. ?

> But I can't get them to show the application icons. default, firefox or thunderbird... all the same.

You right. This works only on Linux.

**Comment by tooomm** [comment]
I was running TB 38.7.2 and FF 45.0.2 (both portable), addon version was 1.9.6 and Win 8.1 with most recent updates (at least very close to). I can tell because I just updated 2 days ago and checked the TB/FF versions today, just installed new TB/FF updates right now - no updates in between.
<br>
>You right. This works only on Linux.

Do you know what the problem on Win is about?

In your picture it looks like icons are shown for Win 8.1 - is this just an issue on Win 10?
![](https://camo.githubusercontent.com/341e5bb4c2a7a86e2482f65c973aa48b3f82985d/68747470733a2f2f7261772e6769746875622e636f6d2f6d6b696f6c2f474e6f7469666965722f6d61737465722f6d6973632f77696e382e706e67)

**Comment by mkiol** [comment]
> Do you know what the problem on Win is about? In your picture it looks like icons are shown for Win 8.1 - is this just an issue on Win 10?

On Linux, you can change the default icon for the "Download complete" and "New Message" notifications using "Notification icon" option. Windows automatically attaches the program icon to the notification, so there is no need to set the app icon in GNotifier's code.

I tested GNotifier both on Win8.1 and Win10 and never had any problems with icons. Maybe the problem occurs only on "portable" versions of FF or TB... I will do some tests and let you know.

**Comment by tooomm** [comment]
I just installed Firefox 46.0 (32bit) on my Windows 10 Pro (64bit). I started with a fresh profile, installed GNotifier 1.9.6 and did a picture download... (changed no settings at all)
![untitled](https://cloud.githubusercontent.com/assets/9874850/14919376/d75a20d0-0e28-11e6-8c78-3a5213062a00.png)

**No app icon for me even with normal Firefox installation!**

**Comment by mkiol** [comment]
It should look like pic below.. I have no idea what is wrong :-/
![virtualbox_win 10_29_04_2016_20_18_46](https://cloud.githubusercontent.com/assets/1420902/14925502/0a837fb4-0e48-11e6-9390-bb5a3b61f29c.png)

Could you please test web notifications as well? [Here](https://github.com/mkiol/GNotifier/blob/master/misc/test.html) is a my test tool - simple html page that generates notifications.

**Comment by tooomm** [comment]
All good... (I used portable Firefox for the test)

![webtest](https://cloud.githubusercontent.com/assets/9874850/14930293/1c586e28-0e63-11e6-93f8-a21659e907ee.png)

**Comment by tooomm** [comment]
Ha, got it! (hopefully...)

While reading [this link](https://github.com/WindowsNotifications/desktop-toasts) posted in https://github.com/mkiol/GNotifier/issues/65#issuecomment-209639876 I found this:
>Be aware that for a desktop app to be able to display toast notifications, that app must have a shortcut on the start menu. That shortcut must have an AppUserModelID.


This made me test the notifications again... I was pretty sure that I disabled "Add entry to start menu" during the Firefox installation. I reinstalled version 46 again with the shortcut in the start menu enabled this time and the app icon was present on the `Download finished` notification! (but with the same "bad" background as on your picture [here](https://github.com/mkiol/GNotifier/issues/104#issuecomment-215839263))
The notification on your testpage however use a nice app icon with transparent background.

**Comment by mkiol** [comment]
> Ha, got it! (hopefully...), I found this...

Thanks for the troubleshooting that you've done!

> but with the same "bad" background as on your picture 

Oh yes, I also noticed it. When icon is automatically added, background is not transparent. That is odd, but this is something that happens inside Windows notification engine, not in GNotifier. In case of web notification, URL for icon is provided by my add-on and the icon's file has transparency and this transparency is displayed correctly.

**Comment by tooomm** [comment]
>In case of web notification, URL for icon is provided by my add-on and the icon's file has transparency and this transparency is displayed correctly.

Couldn't you provide transparent icons with gnotifier as well to make them look nice? ;)

**Comment by mkiol** [comment]
> Couldn't you provide transparent icons with gnotifier

Yes, obviously this comes to my mind but there are following obstacles:
* There are non-Mozilla branded Firefox builds like PaleMoon, WaterFox and others. If I decided to provide FF icons together with GNotifier package, I probably should provide the icons for all other builds as well. It gets complicated :-/
* Mozilla icons are not free. They are protected by trademark policy. GNotifier is released under GPL, and it could be an issue.

**Comment by tooomm** [comment]
Do these other product run into the same problem with their icons? Maybe they provide/include already properly working versions of their icons? I would have to check...
<br>

>Mozilla icons are not free. They are protected by trademark policy. GNotifier is released under GPL, and it could be an issue. 

I'm not too much into the topic, but this is a addon for Mozilla applications and you're not using it out of context, I saw other addons using the official icons to minimize the apps to the tray for example.
Some links that I gathered regarding that, they also provide a contact email for questions.
- official icon source
https://wiki.mozilla.org/Firefox3.5/Logos
- trademark overview
https://www.mozilla.org/en-US/foundation/trademarks/
- trademarc policy (Contact+FAQ at the bottom!)
https://www.mozilla.org/en-US/foundation/trademarks/policy/
- Info about branding
https://www.mozilla.org/en-US/styleguide/identity/firefox/branding/

Another idea, couldn't you just link to a web version of the icon (like you do with your html test notification) and cache/save + reuse it within your addon? Maybe it would do the trick to circumvent the need to provide them in your xpi. Not sure if that changes any legal stuff though.

**Comment by tooomm** [comment]
Any news on this?
Especially on including icons to finally get nice and shiny notifications, since I saw you working with your app icon. :P 👍

**Comment by mkiol** [comment]
Ok, you convinced me. Will be in the next release.

**Comment by tooomm** [comment]
Glad to hear. I'm more than happy to see the next release now, and enjoy good-looking notifications! Awesome. 😃 
<br>
<hr>
Two additional & related things that I realized... 
 - You still have a no longer used icon in the repo: `icon128.png` (you replaced it with `gnotifier.png`)
 - I was wondering about your Iceweasel and Icedove code in L76 and L84 here:<br>
https://github.com/mkiol/GNotifier/blob/master/source/lib/utils.js#L76<br>
Aren't these two debian specific? They got recently replaced by the original ff and tb again afaik.^^

**Comment by mkiol** [comment]
I've uploaded new [1.9.8-pre6](https://github.com/mkiol/GNotifier/tree/master/xpi) XPI. Please try it.

> I was wondering about your Iceweasel and Icedove

Oo, I didn't know that. Thanks for updating me. Finally, they will stop with this "rebranding" stupidity :-) 
Maybe I will keep Iceweasel/Icedove in the code for a while just to have backward compatibility.

**Comment by tooomm** [comment]
Gorgeous! :)

(Btw, is there a reason because you don't close issues once you have resolved them?)

**Comment by mkiol** [comment]
> is there a reason because you don't close issues once you have resolved them

I usually close the issue when release that provides fix is available on AMO, so probably next week.
