### ISSUE TITLE
[SeaMonkey] Download complete notification is not displayed

### ISSUE THREAD

**Issue by rcmero** [mkiol/GNotifier#108]
I believe this is because the download manager in SeaMonkey is different than the one in Firefox. It looks as follows:

![captura de ecra 5](https://cloud.githubusercontent.com/assets/5708421/14882152/0db317b8-0d2f-11e6-9530-f800178d80f9.png)

I also need to test if other notifications are also not being displayed.

**Comment by mkiol** [comment]
Thanks for the report. Will be fixed in the new release.

**Comment by rcmero** [comment]
Did a little bit of testing today and notifications are still displaying (Download Statusbar popped up a notification as expected). It is GNotifier's download complete notification that is not displaying. Hope this helps.

**Comment by mkiol** [comment]
SeaMonkey support should be fixed in the latest [XPI](https://github.com/mkiol/GNotifier/tree/master/xpi). Please check!

Unfortunately, I had to disable the possibility to click on new email notification. Current implementation of this feature doesn't work well on SeaMonkey :-(

**Comment by mkiol** [comment]
Fixed in the latest AMO release - 1.9.8.
