### ISSUE TITLE
[FF+TB] click action on download finished message doesn't focus file on windows

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#109]
The click action should not just open the folder containing the downloaded file, but also pre-select/highlight the new file and scroll to show it... Especially in download folders it's generally a mess to find stuff.

For example: Go to the download history in Firefox (click the arrow icon for downloads in the upper right), right click on a recently downloaded file and choose `Open Containing Folder`.
Firefox will open the containing folder *and* select the file. That's so useful!
The standard Thunderbird notification, if you download an attachment for example, doesn't offer this as well.

**Comment by tooomm** [comment]
FYI:
Even after your "fix" in 86571b0 I experience the same behavior with Thunderbird 45.3.0 on Win 10 and your `gnotifier-1.9.8-pre2.xpi` from [here](https://github.com/mkiol/GNotifier/tree/master/xpi).

I can switch in options between "Open File" and "Open Folder" for `Default click action`.
Both do what they should, but "Open Folder" still doesn't focus/highlight the actual file. It just opens the containing folder.

**Comment by mkiol** [comment]
My mistake, I didn't realize I didn't upload the latest XPI version. Please, try the gnotifier-1.9.8-**pre3**.xpi.

**Comment by tooomm** [comment]
Working now. Awesome! :heart:

**Comment by mkiol** [comment]
Glad I could help :-)

**Comment by mkiol** [comment]
Fixed in the latest AMO release - 1.9.8.
