### ISSUE TITLE
[TB] "Test notification" should also work with a fallback dummy msg

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#113]
If you have no message selected or can't do so because no account is setup for example, there should be a fallback to a simple dummy message to make testing notifications a bit more convenient.

**Comment by mkiol** [comment]
It should be fixed in the latest [XPI](https://github.com/mkiol/GNotifier/tree/master/xpi). Please check it!

**Comment by tooomm** [comment]
Sweet sweet sweet! :sunglasses: 
<br>
![dummy](https://cloud.githubusercontent.com/assets/9874850/15100271/6f6cd002-156d-11e6-8f6b-f1672de78d19.png)
(Besides the ugly and small logo... :laughing: )
