### ISSUE TITLE
[Firefox] Notifications Crash All GNOME Extensions

### ISSUE THREAD

**Issue by ConstruKction** [mkiol/GNotifier#117]
There's always a 50/50 chance of all of my extensions crashing upon receiving a notification.
Once that happens, there's no way to turn them back on unless you log in again, or restart your computer.

I'm on GNOME 3.20 at the moment, and use only one externally-installed extension, which is "Sound input & output device chooser". The rest of the extensions I use are all pre-installed with the gnome-shell package on Arch Linux like User Themes, Windownavigator, and Removable drive menu.

**Comment by mkiol** [comment]
Thanks for the report. I did tests in the similar environment (Arch, GNOME 3.20, Sound input ext) and everything worked fine. I can't replicate the issue :-(

I wonder if this "crash situation" happens only for the specific notification like web notification on certain site, download complete, or always?

**Comment by ConstruKction** [comment]
Ah, perhaps it was good to mention that this usually happens with Google Hangouts integrated within the Inbox app.
Crashes occur on both GNOME on X and Wayland sessions.

Next thing I'll try is disabling Pushbullet, but I'll only have a chance to do so on Monday since it's on my work PC.

**Comment by ConstruKction** [comment]
Err... I just connected my phone to my PC and the native GNOME notification--informing me that a device has been connected--crashed all of my extensions.

Looks like I blamed the wrong tool. Sorry for that! It never happened before with native notifications.
