### ISSUE TITLE
Does not replace firefox notifications created by Gmail Notifier (Restartless)

### ISSUE THREAD

**Issue by AndydeCleyre** [mkiol/GNotifier#121]
Hi,

Using

- GNotifier 1.9.7
- Firefox 46.0.1
- Plasma Desktop 5.6.4
- Arch Linux

Firefox notifications are used, regardless of whether the Notification Engine is set to GNotifier or Standard.

**Comment by mkiol** [comment]
Thanks for the report. 

Could you please try to do following:
- using ``about:config``, add new param ``extensions.sdk.console.logLevel`` with value ``all`` ([here is reference](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/console#Logging_Levels))
- start FF from the terminal and check if output has something significant (e.g. errors, exceptions...)

**Comment by AndydeCleyre** [comment]
Thanks. I've done that, but the output hasn't changed, it's just a few GTK warnings:

```
(firefox:6975): Gtk-WARNING **: Theme parsing error: gtk.css:2249:17: negative values are not allowed.
(firefox:6975): Gtk-WARNING **: Theme parsing error: gtk.css:3973:20: negative values are not allowed.
(firefox:6975): Gtk-WARNING **: Theme directory actions/48 of theme breeze has no size field
(firefox:6975): Gtk-WARNING **: Theme directory categories/16 of theme breeze has no size field
(firefox:6975): Gtk-WARNING **: Theme directory categories/22 of theme breeze has no size field
(firefox:6975): Gtk-WARNING **: Theme directory categories/48 of theme breeze has no size field
(firefox:6975): Gtk-WARNING **: Theme directory devices/48 of theme breeze has no size field
(firefox:6975): Gtk-WARNING **: Theme directory base/ of theme oxygen has no size field
```

**Comment by AndydeCleyre** [comment]
On the computer experiencing this, I'm using an [infinality](https://wiki.archlinux.org/index.php/Infinality) font configuration. It just occurred to me that this might be related.

**Comment by mkiol** [comment]
Hmm.. I wil try to setup environment similar to yours but, honestly, hardly believe that  font configuration is a source of the issue.

**Comment by AndydeCleyre** [comment]
I just set up a new FF profile, added some extensions (including this one), and am still having the issue.

I noticed the custom command option, though. So I set the engine to custom, and made the custom command:

```bash
notify-send -i "%image" "%title" "%text"
```

But this still uses the FF notifications, and sometimes they're even partially off the screen.

So I added that logging level option you mentioned, and here's the output on launch (a notification for email is shown on launch) with the obviously other-extension and non-error stuff filtered out:

```
(firefox:3995): Gtk-WARNING **: Theme directory base/ of theme oxygen has no size field

console.warn: SDK worker-child started as frozen on unexpected initial document.readyState {"initialDocumentReadyState":"uninitialized","windowLocation":"about:config"}
console.warn: SDK worker-child started as frozen on unexpected initial document.readyState {"initialDocumentReadyState":"uninitialized","windowLocation":"about:blank"}
console.warn: SDK worker-child started as frozen on unexpected initial document.readyState {"initialDocumentReadyState":"uninitialized","windowLocation":"about:blank"}
```

**Comment by AndydeCleyre** [comment]
And it's the same behavior with the simpler custom command:

```bash
notify-send "%title" "%text"
```

**Comment by mkiol** [comment]
I made tests  in the following environment and everything seems to be working fine, including "Custom command" and `notify-send -i "%image" "%title" "%text"`...

-     GNotifier 1.9.7
-     Firefox 48.0.2
-     Plasma Desktop 5.7.5
-     Arch Linux

Did you try to test it with the fresh FF profile, without any other add-ons?

**Comment by AndydeCleyre** [comment]
I just created a brand new profile, installed gnotifier, and it worked.

So I went through and added my usual extensions, testing again after each one. It worked.

I went back to my current real-use profile and tested the same way . . . and it worked!

I'm sorry for the noise -- most (if not all) of my firefox notifications come from the Gmail Notifier (Restartless) addon, and I am now realizing it does not use the firefox notification system; I guess it uses its own. I thought I had remembered your extension working with that one, but I was probably mistaken.

Until today all my notification testing was done by clicking the refresh button on that gmail addon.

Thanks for looking at this with me, and sorry again for my ignorant false-testing.

**Comment by AndydeCleyre** [comment]
Hmm, it [looks like](https://github.com/inbasic/ignotifier/issues/417) that extension *does* use FF's notifications.

I'm re-opening, and editing the title to focus on compatibility with that extension.

**Comment by AndydeCleyre** [comment]
Aaaand today, this works.

firefox 49.0
ignotifier 0.6.5
gnotifier 1.9.7

**Comment by mkiol** [comment]
It is "well known" problem that was already discussed in #33. If some add-on is loaded (during FF start) before Gnotifier, notifications will not work. The order in which they are loaded is somehow indeterministic, so from time to time everything works well. The only solution I found is to do very small change in add-on that should interwork with GNotifier.

Let me get back to you later after I review ignotifier source code.
