### ISSUE TITLE
[Thunderbird] Feature request: summarize when multiple messages come in

### ISSUE THREAD

**Issue by blerner** [mkiol/GNotifier#122]
If I've left my laptop asleep for a while, when I resume it, naturally lots of messages get downloaded.  Every single one of them triggers a notification and, when on Linux using the OS-native notifier, I have to wait for every notification to time out before they disappear.  It would be nice to have a single alert saying "32 new messages" or some such, rather than showing me 32 individual notifications.

**Comment by mkiol** [comment]
Thanks for the report. Totally agree. I'm adding it to my TO-DO list.

**Comment by mkiol** [comment]
Requested functionality is in the latest "beta" XPI - [gnotifier-1.9.8-pre3.xpi](https://github.com/mkiol/GNotifier/tree/master/xpi).  

There is a new option ("Maximum number of simultaneous notifications") on the preferences panel where you can define the maximum number of simultaneous notifications for new messages. For instance, "5" (default) means that if you receive less or equal 5 messages at once, all will trigger individual notification, but if you receive more than 5 new messages at once, only 1 aggregated notification will be shown.

**Comment by blerner** [comment]
In the Windows version of TB, when multiple emails come in the toaster notification shows a bit more information: the sender and the beginnings of the subjects of the first few emails.   Could you add a preference, akin to the Title and Text fields, so a user could write e.g.

Multiple-email Title: "%c emails received" (where %c means the count of new messages)
Multiple-email Text: "[%n: %s]{3}" meaning "show the first three emails, showing their sender and subject lines" or something like that.

That would be a bit more informative than "5 messages received", while still not overloading the notification with too much clutter...

**Comment by mkiol** [comment]
> Could you add a preference, akin to the Title and Text fields, so a user could write

OK, it makes total sense. Will be included in the next release.

**Comment by mkiol** [comment]
Enhancement is in the latest AMO release (1.10.0).
