### ISSUE TITLE
Exclude certain folders from notification

### ISSUE THREAD

**Issue by ndeubert** [mkiol/GNotifier#125]
I am wondering if there is a way to tell it to not notify for certain folders. I looked through some of the code and saw this and was wondering how to set a folder as excluded?

source/lib/thunderbird.js:
243         function isFolderExcluded(folder) {

Thanks,
Nick

**Comment by mkiol** [comment]
There is no UI for that, but definitely you can do it by altering the code inside `isFolderExcluded`. Notification is not shown if function returns `true`. Folder API is depicted [here](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIMsgFolder#Attributes). For instance, name of the folder is `folder.name` or `folder.rootFolder.name`...

**Comment by pd5rm** [comment]
I just found out about GNotifer (and really like it so far), but I have the same feature request. A way to either include or exclude folders for notifications. In my case, I only care about receiving updates for Inbox.

I saw the code for isFolderExcluded (/source/lib/thunderbird.js), it would be nice to be able to choose from list of folders in a UI. If I modify the code, I'd have to maintain it for newer releases.

Thanks again!

**Comment by pd5rm** [comment]
Well I tried to extend the package to allow for explicitly listing "included" folders, but failed. ;-(

#127

**Comment by mkiol** [comment]
@pd5rm Thanks for your contribution. Your commits are included in the latest release.

**Comment by pd5rm** [comment]
Thanks! It was a pleasure contributing to your project. ;-)

**Comment by Nick-Deubert-Bose** [comment]
Great! Thanks to both of you.
