### ISSUE TITLE
Windows 10 notification is cleared from action center when notification window closes

### ISSUE THREAD

**Issue by T4GTR43UM3R** [mkiol/GNotifier#126]
In Windows 10 64 bit the notification window appears by default for 5 seconds. After the window disappears the notifications are cleared in the action center. This happens with Firefox 47.0.1 and with Thunderbird 45.2.0.

**Comment by tooomm** [comment]
Same for me!

As long as you don't click the notification to interact with it, it should be collected in the action center.
I guess that's how they are supposed to work?

**Comment by mkiol** [comment]
The issue is already reported in #65 and unfortunately still open. We are waiting for someone brave enough to challenge it :-)

**Comment by T4GTR43UM3R** [comment]
Oh. While browsing the open issues I was a little bit irritated by the title. I thought the notification doesn´t show up anyway.  And I found the issue XD. You have to go to Settings, System, Notifications & actions, click on Thunderbird and enable showing notifications in the action center.
Works.
My bravery is limitless XD.

**Comment by tooomm** [comment]
Well, the setting is there (I didn't know about it before, too!)... but it doesn't change the behaviour for me.

Clicking the notification and letting them time out, both don't make them appear in the action center!
The only way to get them into the action center for me is to click its logo while the notification is shown. 
But then you'll get a weird cryptographic headline... and it'll disappear after the notification itself disappeared: (the setting doesn't change anything here btw!)
![action center](https://cloud.githubusercontent.com/assets/9874850/17101639/f5d4b052-5275-11e6-928f-6c8fccf7525c.png)

Same for you @T4GTR43UM3R ?

**Comment by T4GTR43UM3R** [comment]
The notifications stay in my action center until I click on them to open Thunderbird. This works on several user accounts. Your replay was also shown in the action center.
![action center](https://cloud.githubusercontent.com/assets/20624044/17102455/f6c39ab0-5279-11e6-929b-490bdb6c9475.jpg)

**Comment by tooomm** [comment]
You're using a installed version of Thunderbird?

**Comment by T4GTR43UM3R** [comment]
Yes I am using an installed version. Firefox works too.
My notification settings look like this. It is in german. I had to change the fourth setting to get the notifications stay.
![settings](https://cloud.githubusercontent.com/assets/20624044/17102603/b13affa0-527a-11e6-8810-7670b0c1c7c6.jpg)

**Comment by tooomm** [comment]
Yep... as expected. It works with the installed version of Thunderbird. Portable isn't working though!

That's why I got confused in the windows settings, I have TB installed for testing and therefore it was displayed in the notification settings.
Portable Applications seems not to register there.

**Comment by T4GTR43UM3R** [comment]
I'm glad that it works for you too. But it is strange that it only works with the installed version. I have several other portable apps installed on my pc and there is no problem with notifications.
There must be a proble with Thunderbird.

**Comment by tooomm** [comment]
I use other portable apps with notifications as well, all good.
But none of them show up in the action center as far as I can tell, just the initial normal pop-up.

**Comment by tooomm** [comment]
@T4GTR43UM3R 
It works for me in the meantime for portable Thunderbird. I can't click the notification in the action center  to open thunderbird and focus the message though. It does nothing, not even removing the entry.
Does that work for you?

**Comment by T4GTR43UM3R** [comment]
I have to click on the Thunderbird headline to open.
But my message doesn't get focused too. I'm using sorting by date and grouping by sorting in Thunderbird.
