### ISSUE TITLE
[Thunderbird] Additional feed account creates notifications even with rss setting disabled

### ISSUE THREAD

**Issue by Songworks** [mkiol/GNotifier#128]
In Thunderbird I've created a second rss feed account, but unlike the first one, your great addon creates notifications for this one even though the setting 'Notifications for RSS Feeds' is disabled.

I did a quick look to see how your addon determined if an account is an RSS feed or not and I might have found the problem:

In your source [here](https://github.com/mkiol/GNotifier/blob/master/source/lib/thunderbird.js#L290) it checks if the accounts folders last part equals the string 'Feeds'.
So far I could gather, the first feeds account created in Thunderbird has the name 'Feeds'. But apparently subsequent accounts will not. In my case the new one got called 'Feeds-2-2'.

So, unless I misunderstood something, could you change the line to check if the folders name contains the string 'Feeds' rather than an equal?

Cheers!

**Comment by Songworks** [comment]
Did a quick test locally and changed the [line](https://github.com/mkiol/GNotifier/blob/master/source/lib/thunderbird.js#L290) to:
`var isRSS = (rootURIarr[rootURIarr.length-1].indexOf("Feeds") !== -1);`

Seems to work for me.

**Comment by mkiol** [comment]
You are absolutely right. Thank you for your finding. I will update the code as you suggested.

**Comment by mkiol** [comment]
Fixed in the latest AMO release - 1.9.8.
