### ISSUE TITLE
[Windows] [New feature] Disable notification sound for Windows

### ISSUE THREAD

**Issue by computergeek125** [mkiol/GNotifier#130]
Would it be possible to add an option to disable the Windows notification sound on the popup notifications?  With this addon enabled and Thunderbird set to play its own notification sound, I hear a mix of the Windows notification sound and the default Thunderbird notification sound when I get an email.  Cool as it sounds, I would prefer to just have the Thunderbird auditory cue.

I don't know if this is applicable to other platforms as I have limited experience with Thunderbird on other platforms.

**Comment by mkiol** [comment]
@kabili207 Taking into account capabilities of the Windows action center API, do you thing it is technically possible to disable sound for the notification?

**Comment by kabili207** [comment]
You can disable the sound on a per app basis in the system settings. See option three in this link: http://www.tenforums.com/tutorials/4111-notifications-apps-turn-off-windows-10-a.html

**Comment by kabili207** [comment]
We can also remove the sound on individual notifications. https://msdn.microsoft.com/en-us/library/windows/desktop/hh761492.aspx#no_sound

**Comment by mkiol** [comment]
> You can disable the sound on a per app basis in the system settings. See option three in this link: http://www.tenforums.com/tutorials/4111-notifications-apps-turn-off-windows-10-a.html

@kabili207 Thank you for the solution. 

@computergeek125  So, you can disable  sound for Thunderbird notifications in Settings->Notifications & Actions->Mozilla Thunderbird->Play a sound when notification arrives.

![screenshot_20160821_211656](https://cloud.githubusercontent.com/assets/1420902/17839339/005c1964-67e5-11e6-8614-a2e366199cf8.png)

**Comment by computergeek125** [comment]
Cool.  I did not know that setting existed.  Thanks!
