### ISSUE TITLE
can you add an option?

### ISSUE THREAD

**Issue by apan65** [mkiol/GNotifier#132]
I need to hide notification for files with definite extension.

**Comment by mkiol** [comment]
This kind of option seems useful. Will be in the upcoming update.

**Comment by mkiol** [comment]
Option you requested is in the latest "beta" XPI - [gnotifier-1.9.8-pre3.xpi](https://github.com/mkiol/GNotifier/tree/master/xpi). There is new option ("List of excluded file extensions") on the preferences panel where you can define list of filename extensions that will not trigger Download Complete notification.

Unfortunately package is not signed, so to test it, you will need to use FF dev edition.

**Comment by apan65** [comment]
thanks, i can to sign addon for myself, but simply wait new signed version.

**Comment by mkiol** [comment]
I think it is not possible to sign package by your self. You have to either wait for the addons.mozilla.org update or force FF to install not signed xpi. [Here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_override-add-on-signing-advanced-users) is instruction how to do it.

**Comment by apan65** [comment]
it so easy to sign any addon, i have done it already for test, simply change id http://clip2net.com/clip/m11339/3fff3-clip-35kb.jpg

**Comment by mkiol** [comment]
Wow! I didn’t know it is possible. Thanks!

**Comment by mkiol** [comment]
It is fixed in the latest AMO release.
