### ISSUE TITLE
Any plans to add Firefox multiprocess support soon ?

### ISSUE THREAD

**Issue by ojizero** [mkiol/GNotifier#133]

**Comment by mkiol** [comment]
As far as a I know, Gnotifier is already compatible with e10s. I didn't notice any issues during my tests, but I never know for sure. Please let me know if you faced any issue with multiprocess support. Thanks!

**Comment by ojizero** [comment]
@mkiol the Mozilla Add-on Compatibility Reporter extensions keeps on reporting that GNotifier is not compatible with multiprocess ! And multiprocess was disabled when I first got the update, when I saw the warning from Add-on Compatibility Reporter I didn't enable it ! I'll enable it and see what happens then. Hopefully it works out fine ^_^ thanks for all

**Comment by mkiol** [comment]
You right, Mozilla Add-on Compatibility Reporter says "not compatible", but this indicates only that developer didn't mark that add-on supports multiprocess. I'm preparing an update and the new package will be marked as "compatible". Of course, only if I don't find any issues related to multiprocess.

**Comment by ojizero** [comment]
@mkiol sorry I didn't reply earlier but I wanted to test it before anything ;p I've enabled e10 while keeping GNotifier on for the past couple days and I haven't noticed anything out of the ordinary ^_^ thank you so much for all your work mate :D
