### ISSUE TITLE
[TB] new mail count wrong in notification

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#137]
"New mail count" seems to be actually a "total unread mail" count instead for aggregated new mail notifications. (with 1.9.8-pre3)

I had like 10 new mails in one account after starting Thunderbird, so I got a aggregated info message instead 10 single ones. But it showed me `98` mails (I can't tell anymore if it said new or unread mails though...) instead which is the number of unread mails in all of my accounts.

**Comment by mkiol** [comment]
Fixed in [1.9.8-pre4](https://github.com/mkiol/GNotifier/tree/master/xpi).

**Comment by tooomm** [comment]
Working with `pre4` - Thanks for the quick fix!

**Comment by mkiol** [comment]
Fixed in the latest AMO release (1.9.8).
