### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by lheckemann** [mkiol/GNotifier#142]
This add-on doesn't have any licence terms which define the terms under which people are allowed to use the code. Could you please [fix](http://choosealicense.com/) this?

**Comment by mkiol** [comment]
Thanks for noticing it. 

It is [GPLv3](https://github.com/mkiol/GNotifier/blob/master/LICENSE). I've updated README. License info is as well in the source files and in the [package.json](https://github.com/mkiol/GNotifier/blob/master/source/package.json#L3).

**Comment by lheckemann** [comment]
Thanks! I hadn't checked the source (smart...)
