### ISSUE TITLE
New icon in 1.9.8-pre5 not displayed everywhere

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#145]
It's working in the addon overview:
![icon2](https://cloud.githubusercontent.com/assets/9874850/18817204/5ecba96a-835b-11e6-8b99-e8181d1c9a7f.png)

But not working in the addon "Options"/"More" info area:
![icon](https://cloud.githubusercontent.com/assets/9874850/18817207/65ce1e0a-835b-11e6-85d5-c20cc1a35d46.png)

**Comment by mkiol** [comment]
The icon on details page is fetched from  addons.mozilla.org. I will update AMO data later, together with uploading new release. Please be patent :-)
