### ISSUE TITLE
[FF+TB] congregate dl notifications as well

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#150]
see #122 

GNotifier summarizes several incoming notifications for messages in Thunderbird.
I would like to see the same for "Download finished" notifications.

I just received an email with several files attached. When you hit `Save All` or download all manually you end up receiving single notifications minutes later because they don't get grouped.
This all blocks other (important) notifications from showing and easily annoys you.

---

How could it work?
The first notification needs to display normally. But while it displays others accumulate and could get shown as:

```
title: downloads finished
text: filename1,
text: filename2
...
```

While the first accumulated notfication shows up, other single ones get collected again to show the next summarized one right after.
There could be a (configurable) maximum amount of filenames that get shown, or even a cap on how many get summarized in total until a new congregated notification gets created.
Alternatively the notification could also say "x files" instead listing several file names.
Click action should then highlight no file at all and just open the download folder; or highlight the first downloaded file the notification is mentioning.

**Comment by mkiol** [comment]
Done in [1.10.8](https://github.com/mkiol/GNotifier/tree/master/xpi).
