### ISSUE TITLE
[Thunderbird] "Couldn't reach server" notifications keep repeating

### ISSUE THREAD

**Issue by aph3rson** [mkiol/GNotifier#155]
I'm not sure of the exact text, but if the device isn't connected to the network, GNotifier will regularly repeat (~3min or so) that there's no connection to the server in question.

Could there be a way to disable this functionality?

**Comment by mkiol** [comment]
GNotifier just simply pass to OS every notification that is generated by Firefox/Thunderbird without any repeating. I'm guessing that in your case Thunderbird periodically generates "Couldn't reach server" message. This behavior can't be changed on GNotifier level.
