### ISSUE TITLE
Add a "delete mail" option

### ISSUE THREAD

**Issue by pprw** [mkiol/GNotifier#161]
This is a request feature (for thunderbird). I would be nice to be able to delete an email directly from the notification. If you see a new email which is clearly not interesting for you, I would like to delete it straight with a button close do "open" and "mark as read".

bye

**Comment by pprw** [comment]
Le 07/04/2017 à 20:15, Mkiol a écrit :
>
> Nice idea. I will add it to the next release.
>
Cool ! Thank you !

**Comment by mkiol** [comment]
Please check the latest [gnotifier-1.9.9-preX.xpi](https://github.com/mkiol/GNotifier/tree/master/xpi) package. 

What I added:
* In the settings, "Default click action for E-mail notifications" has new "Delete" option. If you are on Windows, this option sets "click" action. 
* On Linux, every new e-mail notification has 3 buttons: "Open", "Mark as read", "Delete".
* Click on "Delete" marks message as read and moves it to the Trash folder

Let me know what you think.

**Comment by tooomm** [comment]
Is it possible to have for example  a right click menu option on Windows to delete messages as well right from the notification?

**Comment by mkiol** [comment]
@tooomm I'm forwarding your question to @kabili207 (He is an author of GNotifier's windows integration).

Questions:
- Is it possible to have right click action on windows notification?
- Is it possible to have buttons on notification (something similar to what is possible on Linux)?

![kde_notification](https://cloud.githubusercontent.com/assets/1420902/25314045/434421aa-283c-11e7-83e2-e09147b02d2c.png)

**Comment by kabili207** [comment]
Unfortunately, adding buttons can't be done without switching from the Windows 8 API to the Windows 10 API, which is problematic for all the reasons I've outlined in [this comment on issue 65](https://github.com/mkiol/GNotifier/issues/65#issuecomment-154482748). Right-click actions aren't possible in either API.
