### ISSUE TITLE
Not extremely important, but...

### ISSUE THREAD

**Issue by ai-da-kn** [mkiol/GNotifier#165]
I noticed a misspelling and I think you should fix it so your extension looks more professional.
![image](https://cloud.githubusercontent.com/assets/23557519/25365360/3318626e-2936-11e7-9a65-541cd5d30671.png)

**Comment by mkiol** [comment]
Thanks for the report. Actually this typo is fixed in the latest version (1.10.0). This version is waiting to be accepted by the Mozilla review team and should be available on addons.mozilla.org in a few days.
