### ISSUE TITLE
When click the notification to "Select on list", the fold is not right

### ISSUE THREAD

**Issue by parr0tr1ver** [mkiol/GNotifier#169]
When click the notification and the setting is to "Select on list", then new email is selected. But the previous fold is kept in "Folder panel". The folder contains the new email should be selected.

Thanks.

**Comment by parr0tr1ver** [comment]
Duplicated to #147

**Comment by mkiol** [comment]
It should be fixed in the latest [dev](https://github.com/mkiol/GNotifier/tree/master/xpi) xpi.
