### ISSUE TITLE
Extension makes nothing

### ISSUE THREAD

**Issue by breadlesscode** [mkiol/GNotifier#170]
I can click on test but nothing happens. I tried standard as notification engine but nothing happens. 

System uses  notify-send.

I use Deepin OS 15.4 witch is based on Debian unstable. 

How can I debug this extension?

**Comment by mkiol** [comment]
Thank you for the report. 

Could you please provide me:
- Application and version (e.g. Thunderbird 52, Firefox 51...)
- GNotifier version (1.9.8, 10.1.0...)

**Comment by breadlesscode** [comment]
Thunderbird: 45.7.0
GNotifier: 1.10.0

Thanks you =)

2017-05-17 9:25 GMT+02:00 Mkiol <notifications@github.com>:

**Comment by mkiol** [comment]
I found cause of the problem. GNotifiers checks what functionality is able to provide notification-server installed in the OS. There is a [dbus API](https://developer.gnome.org/notification-spec/#org.freedesktop.Notifications.GetCapabilities) to get server capabilities. Unfortunately notification server installed in Deepin advertises no capabilities at all. It is a bug in Deepin.

(Just for science) I've prepared [modified XPI](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.10.4-deepin.xpi) with capabilities check disabled. As you can see It works, so it seems that the only problem is in this GetCapabilities API not in functionality.

**Comment by breadlesscode** [comment]
OK thanks! =)
