### ISSUE TITLE
Web extensions are the future!

### ISSUE THREAD

**Issue by rugk** [mkiol/GNotifier#171]
The current plan is that Firefox 57 will only support [web extensions](https://wiki.mozilla.org/WebExtensions). Your add-on is not a web extension yet as far as I can see, so you should consider remaking your add-on. The Firefox 57 release is [planned for 28th November 2017](https://wiki.mozilla.org/RapidRelease/Calendar).
Already for Firefox 53 (planned release: 18th April 2017) it is planned to no longer accept other new add-on submissions than web extensions on AMO (addons.mozilla.org). Old extensions can however still be updated.
The good message is that one should be able to use your web extensions add-on in all mayor browsers. That's the idea behind web extensions.
Note that you can use so-called [hybrid extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) for switching to WebExtensions.

Note that all dates are estimates and may be changed.

German source: https://www.soeren-hentzschel.at/firefox/firefox-57-mit-exklusiver-webextension-unterstuetzung/
Original source: https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

**Comment by mkiol** [comment]
Thank you for bringing WebExtensions topic up. 

To be perfectly honest I really like the idea to have common standard for extensions development across all browsers. Unfortunately with strengths of WE (for instance portability and security) also comes limitations. 

Currently API in WE framework doesn't allow to do many things that are essential for GNotifier. Therefore, from strictly technical reasons, it is impossible to reimplement GNotifier as WE. I wish I could do it, but it is simply impossible.

**Comment by rugk** [comment]
Yeah, okay. At least in Fedora it already seems to work without this extension.

**Comment by mkiol** [comment]
Exactly! As I wrote in #162, most Linux distributions already enabled built-in integration with notification-server, so GNotifier is not needed any more.

**Comment by rugk** [comment]
Ah, all right. So basically this is a dupe of https://github.com/mkiol/GNotifier/issues/162.
