### ISSUE TITLE
Message rules moving emails from inbox break notification

### ISSUE THREAD

**Issue by SillonBono** [mkiol/GNotifier#173]
Hi,

I'm running Ubuntu 16.04.2 and Thunderbird 52.1.1

Since the last update to gnotifier (1.10.0) notification for emails that are moved to another folder from the inbox via message rules do not display any content.

The appear with the line "[Empty subject]" and nothing else.

I had not observed this problem with the previous version.

If I can do anything to help debugging this, please let me know, I'm not a developer but can follow instructions.

**Comment by mkiol** [comment]
Thank you for the report. It looks like something similar to #166 but not narrowed only to spam messages. 

Could you please give me more information about your Message Filters configuration? I tried to recreate the issue but it seems that everything is working fine on my TB - I'm receiving notifications from messages moved from Inbox to other folders.

**Comment by SillonBono** [comment]
Hi,

The nature of the filters is the typical you can expect, if something arrives with condition X move it to folder Y, I have 40+ filters though.

The account is IMAP, the folder structure where I move the emails is 

mailbox->alerts->alert_type1
mailbox->alerts->alert_type2
mailbox->alerts->alert_type3
etc.

Different rules move emails into these folders, all of them are contained within the IMAP mailbox, none of the filters move anything to a local folder or a folder in another place other than the IMAP mailbox itself.

Hope this is of help.

If I can provide more info, please let me know.

**Comment by SillonBono** [comment]
I have read the description for issue #166, do you think I should try the version commented there to see if it makes a difference?

**Comment by mkiol** [comment]
With this ac5acfc0278df45d491fbf397979628ae0e01bb5 commit I changed the way how GNotifier detects new messages. I think the problem with "Empty" messages should be resolved. Please try newest dev [XPI](https://github.com/mkiol/GNotifier/tree/master/xpi) and report here if the issue still exists or not.

**Comment by SillonBono** [comment]
Hi mkiol,

Yay! it fixes it, thank you very much!

**Comment by mkiol** [comment]
Issue resolved in 1.10.5 release.
