### ISSUE TITLE
xfce4-notifyd issue

### ISSUE THREAD

**Issue by hinxx** [mkiol/GNotifier#177]
I'm getting these lines in /var/log/syslog for every notification of e-mail:

`Jun 15 10:47:30 comp org.freedesktop.Notifications[2834]: (xfce4-notifyd:13649): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 2 char 1: 'xxx@yyy.zzz' is not a valid name: '@'
`

I'm not sure if there is anything wrong.. I get these notifications:

![screenshot_2017-06-15_10-58-33](https://user-images.githubusercontent.com/2725009/27173777-1c1f5e30-51ba-11e7-8813-6e8a38b46593.png)

This is on XFCE, Linux mint, GNotifier 1.10.5, TB 52.2.0.

**Comment by mkiol** [comment]
Thank you for the report. 

It looks quite weird. I see at least two issues:
- Duplicated new mail alert
Your screenshot shows 2 alerts for new message. The top one is generated by TB and the bottom is from GNotifier. Could you please check in `about:config` what is a value of `mail.biff.show_alert`? To open `about:config` you probably need to install addon, for instance this [one](https://addons.mozilla.org/en-US/thunderbird/addon/more-about/).
- Error/warning in xfce4-notifyd
To troubleshot that start in terminal `dbus-monitor` and then generate notification that causes issue. Send me output from terminal.

**Comment by hinxx** [comment]
Thanks for looking into this @mkiol .
* mail.biff.show_alert;false
* dbus-monitor output is attached [email_notification.txt](https://github.com/mkiol/GNotifier/files/1087227/email_notification.txt)

**Comment by hinxx** [comment]
Ups, I had another notification plugin installed alongside GNotifier. After removing the other one I get a single pop-up and no dbus errors appear when using GNotifier! Sorry for the noise..
