### ISSUE TITLE
Integrate into default Thunderbird

### ISSUE THREAD

**Issue by orschiro** [mkiol/GNotifier#178]
This is such a great add-on that I am wondering why it's not being integrated into default Thunderbird?

https://bugzilla.mozilla.org/show_bug.cgi?id=1376702

https://bugzilla.mozilla.org/show_bug.cgi?id=1358837

**Comment by mkiol** [comment]
Thanks! 

I've read your bug reports. Honestly I didn't know that there is hidden option to enable libnotify'd notifications! It is cool but unfortunately this capability is very limited. The biggest advantage of GNotifier is very flexible configuration which you don't have using built-in alerts. For instance:
- buttons: Open, Mark as read, Delete
- patterns to customize content of alert (author, subject, body...)
- aggregation of many notification in to one
and more...

**Comment by orschiro** [comment]
I agree, your implementation is superior. 

Do you think we can integrate your add-on into the core of Thunderbird?

The Thunderbird developers are open for the contribution and integration.

**Comment by mkiol** [comment]
> I agree, your implementation is superior

Thanks :-D

> Do you think we can integrate your add-on into the core of Thunderbird?

I will consider it but I'm not fully convinced. TB has its own implementation of native notification and maybe it is better to have optional add-on if someone needs more configurable solution.

**Comment by orschiro** [comment]
> I will consider it but I'm not fully convinced. TB has its own implementation of native notification and maybe it is better to have optional add-on if someone needs more configurable solution.

I will leave this up to you. You may want to ask for their opinion on the bug tracker tickets I linked to in my first comment. :-)
