### ISSUE TITLE
Add archive option to notification?

### ISSUE THREAD

**Issue by orschiro** [mkiol/GNotifier#181]
Is this possible? :-)

**Comment by mkiol** [comment]
Like new "Archive" button on notification bubble? Possible.

**Comment by orschiro** [comment]
Yes exactly this! :)

What do you think?

**Comment by mkiol** [comment]
I'm scheduling it for the next release.

**Comment by orschiro** [comment]
Cool thanks so much! When is the next release due more or less?

**Comment by mkiol** [comment]
2 weeks, more less...

**Comment by orschiro** [comment]
Excellent! :-)

**Comment by mkiol** [comment]
Archive button feature is ready. Try [gnotifier-1.10.7-dev.xpi](https://github.com/mkiol/GNotifier/tree/dev/xpi) from dev branch.

**Comment by orschiro** [comment]
Just tested. Works great. Thank you! :-)
