### ISSUE TITLE
Notification duplicate

### ISSUE THREAD

**Issue by Yanpas** [mkiol/GNotifier#183]
OS Linux Mint 18.2, Thunderbird 52.2.1 (64bit)

After receiving Gmail mail I get two exact same notifications. Notification engine: GEngine

**Comment by Yanpas** [comment]
I've tried to mail myself from another mailbox: I do not see duplicates, but when I received mail from `bugzilla-daemon@eclipse.org` - I have seen duplicate

**Comment by mkiol** [comment]
Thanks for the report. It looks very strange.

What is GNotifier version?
Is this bug always reproducible?
What other add-ons are installed in your TB?

**Comment by Yanpas** [comment]
Gnotifier 1.10.5, yes it's always reproducible with messages from bugzilla.

Here are other add-ons
![image](https://user-images.githubusercontent.com/7345761/29471968-c22ef858-845a-11e7-8bf5-1e03dc90c75c.png) (first one is google calendar provider)

Notifications are disabled in thunderbird settings

**Comment by Yanpas** [comment]
Same for trac. In both cases I had message with the same subject in the inbox dir

**Comment by Yanpas** [comment]
Reproduced on windows too (again Eclipse's bugzilla). Seems there is something specific with my inbox. Maybe cache notifications with identical  bodies and headers?

**Comment by mkiol** [comment]
I've checked eclipse's bugzilla emails and can't reproduce the problem. Probably it is related to your specific Inbox configuration. Can you specify what subfolder rules/filters you have configured?

**Comment by Yanpas** [comment]
I've watched my addons list on windows and there is no GNotifier! So it's thunderbird's bug.

I have classical gmail inbox with filter ` to:($ADDRESS@gmail.com)Action: Add to Forums category`

**Comment by Yanpas** [comment]
I've found the root of the issue (I've double-clicked both notifications). When I receive some mails their copies appear in "Important" folder. This copy results in second notification
