### ISSUE TITLE
[Feature Request] List of inboxes to exclude

### ISSUE THREAD

**Issue by MrLewk** [mkiol/GNotifier#186]
I see in the options you can define a list of inboxes to *include* in the notifications, but it would also be useful to have the reverse possible too. 

At work I have a lot of inboxes to monitor, but don't need notifications from only a few. So it'd be easier to make a list to exclude, rather than type out 10+ inbox and folders to be notified by.

**Comment by mkiol** [comment]
Sounds rational. Adding to the roadmap. Thanks!

**Comment by mkiol** [comment]
Implemented in 1.12.2 release (awaits for the AMO review)
