### ISSUE TITLE
[Firefox] GNotifier 1.11.0 is marked as outdated

### ISSUE THREAD

**Issue by codefuhrer** [mkiol/GNotifier#187]
Seems like the current version doesn't support AMO.

[![2017-09-09](https://user-images.githubusercontent.com/2178368/30242063-2e5222be-9598-11e7-93d1-a60db3eb51b0.png)](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/versions/)

See also: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing.

**Comment by tooomm** [comment]
you might want to read https://github.com/mkiol/GNotifier/issues/162

**Comment by codefuhrer** [comment]
Yeah, I think this issue can be considered as dupe.
