### ISSUE TITLE
structure descriptions and pretty print settings more

### ISSUE THREAD

**Issue by tooomm** [mkiol/GNotifier#195]
![settings](https://user-images.githubusercontent.com/9874850/31778206-5f3350e8-b4f0-11e7-916d-4a8fc8f723fb.png)

It's really difficult to parse and find the needed options within all this %'s.

If you can't use some kind of tool tip for example, it would be helpful to have like a table:
%s --> Subject
%n --> Sender Name
%u --> Account

I know that would make the settings page longer, but more useful.

**Comment by mkiol** [comment]
I fully agree with you... I'm slowly becoming convinced to #135 ;-)

**Comment by mkiol** [comment]
I did some improvements in the latest dev xpi.

**Comment by tooomm** [comment]
It looks way clearer 👍
