### ISSUE TITLE
Support for Solaris 11.4

### ISSUE THREAD

**Issue by brmcc** [mkiol/GNotifier#208]
Now that Solaris 11.4 comes with the GNOME 3.24 shell, this extension works great!  It was a pain to install though as it's not a supported platform right now.  Is it possible you could allow Solaris systems to install?

**Comment by mkiol** [comment]
Hello and sorry for veeery late reply. 

Unfortunately due to [some](https://github.com/mkiol/GNotifier/issues/207) reasons, this project is not longer supported. It is incompatible with recent Firefox or Thunderbird versions and there won't be any new release that will fix it.
