### ISSUE TITLE
GNotifier must process the message body

### ISSUE THREAD

**Issue by ssokolow** [mkiol/GNotifier#24]
My tests show that GNotifier is passing through the message body verbatim. Unfortunately, notification daemons don't expect HTML and many react poorly.

(This is a common mistake people make since Pango markup borrows certain common tag names like `<b>` from HTML but is not actually HTML.)

For example:
- The `notification-daemon` reference implementation which Lubuntu 12.04 uses applies XML-style strict parsing rules and, if there's markup it doesn't recognize, it displays a blank message.
- GNOME Shell apparently displays anything but `<b>`, `<i>`, and `<u>` as literal plaintext.

According to the Web Notifications spec, "The user agent must process any markup in this string so that it appears as plain text when used as a string in the underlying notification platform."

On [Bug 858519](https://bugzilla.mozilla.org/show_bug.cgi?id=858919) in Bugzilla, I've gone into detail on what the restrictions are and proposed an approach to performing said transformations.

**Comment by mkiol** [comment]
Finally, the issue has been fixed in the latest dev xpi. It took me only 4 years! ;-)
