### ISSUE TITLE
Temporary icon files are not (always) removed automatically

### ISSUE THREAD

**Issue by dkadioglu** [mkiol/GNotifier#34]
I stumbled upon the problem that the temporary icon files are not deleted automatically. In the end the /tmp folder fills up with many many 0B files like gnotifier-cOwLfp. For me it seems that if there is no icon the temp file is 0B big and is not deleted automatically. If there is a image and the file size is bigger than 0B it is deleted as it should be the case. If you need further info, please ask.

**Comment by dkadioglu** [comment]
I again have that problem, at least since I'm using the 1.9.0pre versions of GNotifier. I have no idea why that happens, sorry. Could you reopen the issue and have a look into it, please. Thanks in advance.

**Comment by mkiol** [comment]
Please take a look on [1.9.0-pre4](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre4.xpi). All temp files (gnotifier-*) should be removed on extension unload. Practically, it means that Gnotifier clears temp files every time when Firefox closed.

**Comment by dkadioglu** [comment]
The deletion after shutdown works. But why have you commented out the deletion after two seconds? I edited the source code and enabled that part again so now temp files SHOULD be deleted after two seconds and eventually missed temp files WILL be deleted during shutdown. Maybe that's a compromise until there is a better solution.

**Comment by mkiol** [comment]
> Maybe that's a compromise until there is a better solution.

OK :-)

**Comment by mkiol** [comment]
Fixed in 1.9.1 release - [AMO link](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/versions/1.9.1)
