### ISSUE TITLE
[Thunderbird] Clicking on new-email notification bubble should open Thunderbird window

### ISSUE THREAD

**Issue by mkiol** [mkiol/GNotifier#35]
The notification for Thunderbird shows up perfectly, but it simply disappears when clicked. The expected behavior would be that clicking it would take you to the Thunderbird window.

**Comment by logos88** [comment]
This would be very helpful

**Comment by Menti** [comment]
This is what I tried to report in my comment to issue #9 
https://github.com/mkiol/GNotifier/issues/9#issuecomment-56733367

**Comment by mkiol** [comment]
Thanks to #99, clickable notification with buttons are now supported. Please try the latest [xpi](https://github.com/mkiol/GNotifier/tree/master/xpi) package.
