### ISSUE TITLE
Not working on Firefox 34 with Ubuntu 12.04

### ISSUE THREAD

**Issue by EmptyStackExn** [mkiol/GNotifier#41]
Hello,

This add-on looks great but does not work completely on my machine (quite different from bug #39). When I download something, then the notification correctly appears with `notify-osd`. However, when I use the [Android Desktop Notifications](http://projects.hcilab.org/notification/) addon (to get my phone notifications on Firefox), those Firefox/XUL notifications are not "transfered" to libnotify.

![xul](https://cloud.githubusercontent.com/assets/1613250/5667815/07e55930-976b-11e4-95d5-f7b10974da38.png)

I am using **Firefox 34.0** and **Ubuntu 12.04** on **GNOME 3 Session Fallback**. Here is my machine configuration : 
- Firefox 34.0
- GNotifier 1.8.7 - Debug Version 
- Linux 3.2.0-75-generic
- libnotify 0.7.5-1

I don't know if this might help but the following message appears on a terminal when I installed GNotifier : 

    console.log: gnotifier: Linux
    console.log: gnotifier: exports.main
    console.log: gnotifier: system.name: Firefox
    console.log: gnotifier: Notify server name: notify-osd
    console.log: gnotifier: libnotify server info:
    console.log: gnotifier: name: notify-osd
    console.log: gnotifier: vendor: Canonical Ltd
    console.log: gnotifier: version: 1.0
    console.log: gnotifier: spec_version: 1.1
    console.log: gnotifier: libnotify server capabilities:
    console.log: gnotifier: body
    console.log: gnotifier: body-markup
    console.log: gnotifier: icon-static
    console.log: gnotifier: image/svg+xml
    console.log: gnotifier: x-canonical-private-synchronous
    console.log: gnotifier: x-canonical-append
    console.log: gnotifier: x-canonical-private-icon-only
    console.log: gnotifier: x-canonical-truncation
    console.log: gnotifier: private-synchronous
    console.log: gnotifier: append
    console.log: gnotifier: private-icon-only
    console.log: gnotifier: truncation
    console.log: gnotifier: notifApi.checkAvailable is ok
    console.log: gnotifier: Expected exeption if FF>=26

**Comment by mkiol** [comment]
Thanks for your report. It is "well known" problem. The only solution is to do change in 'Desktop Notifications for Android' add-on. Fortunately, it was quite easy and [here](https://github.com/mkiol/GNotifier/raw/master/misc/desktop_notifications_for_android-2.0.5-fix_for_gnotifier.xpi) is patched version. Please test it and If it works, I will write to developer explaining what needs to be done to make it compatible with Gnotifier.

**Comment by EmptyStackExn** [comment]
Perfect ! This works great. Thank you ! :+1:

**Comment by mkiol** [comment]
I've got confirmation from hciLab that necessary changes to support for GNotifier will be (likely) added in the next release of  'Desktop Notifications for Android' add-on. Cool :-)

**Comment by EmptyStackExn** [comment]
Thanks !
