### ISSUE TITLE
encoding parameter of class_addMethod is wrong

### ISSUE THREAD

**Issue by Noitidart** [mkiol/GNotifier#42]
Hi there,
I was learning objc in jsctypes and thanks to help and discussion from [@arai-a](https://github.com/arai-a) we think that the `class_addMethod` implementation here last argument is wrong.

We think that the encoding should be:

> so our conclusion is that we have to have a minimum of 3 chars so in summary: first char is return. second is the first arg for C which is always `id`, and third char is second arg of C which is always `sel`. and then the characters following are the 1st,2nd,3rd,nth objc args 

So the code here: [](https://github.com/mkiol/GNotifier/blob/06dad9814d2ac842c359152950b1122874aff2b2/lib/osx.js#L93)

should change from:
``` javascript
let r = class_addMethod( delegate, shouldPresentNotification, callback, "{NSUserNotification=#}");
```
to
``` javascript
let r = class_addMethod( delegate, shouldPresentNotification, callback, "B@:@");
```

What were your thoughts when you thought to use `{NSUserNotification=#}`, your thoughts would help us all learn :)

**Comment by Noitidart** [comment]
Some disucssion between me and arai:

```
10:41	noida	I think he might say his encoding should be `B@:{NSUserNotification=#}
10:42	noida	which im thinking might be right, what do you think?
10:43	noida	if thats right do you think for scrensaver i should use `v@:{NSNotification=#}` ?
10:43	arai	I think "B@:@" is right
10:43	arai	"{...}" is structure. not a pointer to the structure
10:44	noida	AH!!
10:44	arai	"^{...}" might be
10:45	arai	but not sure when such information could be used
10:45	noida	ahh that makes sense too
10:46	noida	so his situation may be `v@:^{NSUserNotification=#}`?
```

**Comment by mkiol** [comment]
Thanks for the update. 
> What were your thoughts when you thought to use {NSUserNotification=#}, your thoughts would help us all learn :)

As far as your question is OSX related, I would ask @kennydude to answer.

**Comment by kennydude** [comment]
I threw together this code, and I don't know a lot about Objective C internals. I saw it as "it worked" and left it at that.

Also Firefox for a few versions now has supported native OSX notifications so I haven't looked into this.

**Comment by Noitidart** [comment]
Thanks @kennydude for that note. It was still awesome code that I learned a ton from!! do you have any other objc code that you could share? :)

**Comment by kennydude** [comment]
I don't have anything playing around with the internals of Objective-C I'm
afraid

**Comment by Noitidart** [comment]
No problem thanks for the replies :)

**Comment by Noitidart** [comment]
This one should still be fixed :P Like it should use `B@:@` :)
