### ISSUE TITLE
[Thunderbird] Sender and subject sometimes are not included in a notification

### ISSUE THREAD

**Issue by mkiol** [mkiol/GNotifier#45]
New email notification sometimes contains only "Number of unread messages: XX" instead sender and subject info.

**Comment by orschiro** [comment]
Thanks for creating a distinct thread. Have you been able to track the issue further down? Can you or someone else replicate the notifications?

**Comment by mkiol** [comment]
It happened to me once and I managed to collect logs. I am still debugging this issue but have a first theory about cause. I need to check it more deeply.

**Comment by mkiol** [comment]
Take a look at my latest xpi: [gnotifier-1.8.8-pre1.xpi](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.8.8-pre1.xpi). I think I found the problem and the fix.

**Comment by orschiro** [comment]
Many thanks! Just upgraded and will test it for the next days to report 
back.

Regards,

Robert

On 01/31/2015 01:42 PM, Mkiol wrote:
>
> Take a look at my latest xpi: gnotifier-1.8.8-pre1.xpi 
> <https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.8.8-pre1.xpi>. 
> I think I found the problem and the fix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mkiol/GNotifier/issues/45#issuecomment-72316283>.
>

-- 
Aspiring sustainability researcher /
Passionate about #sustasty lifestyles /
#transitions #opensource #degrowth /
Love #bouldering /

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by orschiro** [comment]
I did some testing. Indeed, it is no longer showing the general `New message` notification. However, it now displays a new message notification next to the notification about an older email (not opened yet, thus unread). I don't know whether this can be optimised to only show a notification for the latest, new incoming email?

![image](https://cloud.githubusercontent.com/assets/170947/5992249/84e67cca-aa21-11e4-83cc-d34f8d5085a9.png)

**Comment by mkiol** [comment]
That's strange. Firstly, it should display notification with latest "new message". New message is message taken form attribute `firstNewMessage` on [inbox folder](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIMsgFolder#firstNewMessage). In my case it is always correct message. Secondly, I don't know why you have more than one notification. It should be one notification per e-mail account. Maybe notifications are from different accounts?

**Comment by orschiro** [comment]
I think my Thunderbird somehow behaves strangely, maybe due to 
conflicting add-ons?

For the last two days, the issue has gone.

So please, consider this as fixed!

Thankfully,

Robert


On 02/01/2015 06:39 PM, Mkiol wrote:
>
> That's strange. Firstly, it should display notification with latest 
> "new message". New message is message taken form attribute 
> |firstNewMessage| on inbox folder 
> <https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIMsgFolder#firstNewMessage>. 
> In my case it is always correct message. Secondly, I don't know why 
> you have more than one notification. It should be one notification per 
> e-mail account. Maybe notifications are from different accounts?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mkiol/GNotifier/issues/45#issuecomment-72374559>.
>

-- 
Aspiring sustainability researcher /
Passionate about #sustasty lifestyles /
#transitions #opensource #degrowth /
Love #bouldering /

Flying is old-school and the
world cannot be saved part-time

Co-Creator of @MindfulMeerkats

www.robert.orzanna.de
twitter.com/@orschiro

**Comment by mkiol** [comment]
Ok, so I'm closing this issue.
