### ISSUE TITLE
Firefox freezes on Windows 8.1

### ISSUE THREAD

**Issue by brwolfgang** [mkiol/GNotifier#50]
When clicking the notification to open the file Firefox will open the file then freeze for 2~3 minutes, dropping its CPU usage to 0 and memory to ~30 MB. I'm running Firefox 36.0.1 but the problem is noticeable for a while now (I believe it's as old and 34).

I have noticed that pages that trigger notifications (such as 9gag upvotes and comments) also cause Firefox to freeze.

When I disable GNotifier no native notification is shown and Firefox doesn't freeze anymore.

**Comment by mkiol** [comment]
Thanks for the report. I will investigate and get back to you.

**Comment by mkiol** [comment]
I can confirm this issue. I'm observing the same problem on my Windows box.

**Comment by kabili207** [comment]
This looks like it's caused by the clicked/closed handler. Whenever I remove the code that sets the callbacks it works fine.

**Comment by mkiol** [comment]
I was testing it for a few hours. This 'freeze' bug is quite non-deterministic. Sometimes it appears several times in a row and sometimes everything works fine all the time. Ehhh... When 'freeze' happens, callback functions are not triggered, so I suspect that cause of issue could be somewhere inside DLL. @kabili207 What do you think about it?

As a temporary workaround, I've disabled callback functions in [1.8.9-pre1 release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.8.9-pre1.xpi). @brwolfgang I would be grateful if you could test it.

**Comment by brwolfgang** [comment]
@mkiol I'm gonna give it a try and report soon

**Comment by brwolfgang** [comment]
It looks like the issue is gone, the notifications pop-up and go away smoothly as expected.
Not sure if it will work for everyone, but at least for me it works fine.
Good job!

**Comment by mkiol** [comment]
Thanks to @kabili207, bug was fixed (without workaround) in [1.8.9-pre2 release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.8.9-pre2.xpi). 

@brwolfgang Please, check if it works for you.

**Comment by brwolfgang** [comment]
After exhaustive testing I can say it's working fine, sorry for the long time to answer
