### ISSUE TITLE
tmp subdir

### ISSUE THREAD

**Issue by bewam** [mkiol/GNotifier#52]
Hello,

Thanks for your work.
Would it be possible to create a subdirectory in the /tmp dir or delete your "gnotifier-" just created ?
If not, can I delete them through a cronjob ?

**Comment by mkiol** [comment]
In general, "gnotifier-" temp files should be deleted automatically just 
after notification is shown. If not, probably it is a bug. I'll try to 
fix this in next release.

As a workaround solution, yes, you can delete them using cronjob. I 
don't see any objectives.

**Comment by mkiol** [comment]
Here is new [release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre6.xpi). Now, all temp files (gnotifier-*) should be removed on extension unload, so every time when Firefox closed.

**Comment by mkiol** [comment]
Fixed in 1.9.1 release - [AMO link](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/versions/1.9.1)
