### ISSUE TITLE
Download notifications on Linux should contain options to open folder and open file

### ISSUE THREAD

**Issue by DoctorJellyface** [mkiol/GNotifier#54]
Right now you just get a plain notification with one default action set. However in most cases you need an option to either open the file or the folder, e.g.:
1. You download several images in a row. You don't want them all in your Downloads folder. so you want to go into the folder and move them.
2. You download an archive, and you want to directly look inside it.

Of course not all notification servers support this, like Unity's `notify-osd`. However, under the GNOME Shell and possibly Plasma this would be a great feature.

Thanks.

**Comment by mkiol** [comment]
Thanks for the suggestion. I really like your idea. I'm scheduling this feature for the next release.

**Comment by DoctorJellyface** [comment]
Thanks!

**Comment by mkiol** [comment]
It took me some time, but here is [new release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre3.xpi). You should have "Open file" and "Open folder" buttons on notification bar. 

@DoctorJellyface I would be very grateful if you could test it and give me some feedback.

**Comment by DoctorJellyface** [comment]
Just tried, works great. Sorry for the delay. Last time I tried some weeks ago it crashed because of #59 but now it's fine. I think it's good for public release. Thanks very much for this feature!

**Comment by DoctorJellyface** [comment]
BTW, open file should be default, it's more intuitive.

**Comment by mkiol** [comment]
Here is new [release](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.0-pre6.xpi). Open file is now default and libnotify handling is far more stable, so I really hope the crashing issue is fixed.

**Comment by DoctorJellyface** [comment]
Awesome!

**Comment by DoctorJellyface** [comment]
OK, tested it, works fine. Thanks!

**Comment by DoctorJellyface** [comment]
Final thing, meybe it should be in a seperate bug report: the firefox download icon is still blue even after interacting with the notification.

**Comment by cyberalex4life** [comment]
we should be able to activate or deactivate this, sometimes, in GS-3.16 I just wanna click on the notification to disappear, not to open anything.

**Comment by DoctorJellyface** [comment]
Give me an example of a GS notification that uses dismiss as the main action. Btw when I want notifications to disappear I just move my mouse over them.

**Comment by cyberalex4life** [comment]
Well I have some scripts of mine that show a notification and I can click on  it to close, but there is another app: Unified Remote that doesn't do anything on click because it just starts a server.  Anyway, I've already modified the code to do nothing.

**Comment by mkiol** [comment]
Fixed in 1.9.1 release - [AMO link](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/versions/1.9.1)

**Comment by DoctorJellyface** [comment]
Also I've been thinking that the notification shouldn't show when the file is opened, not downloaded, is it possible?
