### ISSUE TITLE
[thunderbird] Make the text displayed in notification more relevant

### ISSUE THREAD

**Issue by Mno-hime** [mkiol/GNotifier#62]
Since Thunderbird 38 messed up Linux libnotify support I have to use GNotifier, and it's great addon! However, I'd like the notification looked more like it used to on pure Thunderbird 31.7.

This is a notification I can see on Fedora 22 with GNotifier 1.8.9.1:

![notification](https://cloud.githubusercontent.com/assets/4632197/8910611/145842d0-3488-11e5-98d9-acba95b2556a.png)

I'd suggest that "New message!" text is a "clutter", because seeing Thunderbirds icon here, I can safely assume I have a new email, no need to tell me again. I'd suggest a new design of the notification (`summary` and `body` terms are from `notify-send --help`) to look more like this:

```
SUMMARY: $subject
BODY: $from writes: "$body_excerpt"
```

![new_notification](https://cloud.githubusercontent.com/assets/4632197/8910986/21b5ec6e-348a-11e5-93c5-46456935e483.png)

...via:

`notify-send -i thunderbird "This is a subject" "Michal Nowak <newman.x@gmail.com> writes: \"Here comes the body...\""`

**Comment by mkiol** [comment]
Thank you for your suggestion, I really like the idea. Scheduled for next release.

**Comment by mkiol** [comment]
Latest commit #96 made by @gabrielfin brings possibility to customize e-mail notifications. I think it gives you enough flexibility to define whatever layout you like to have. Please check newest [xpi](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.6-pre3.xpi).
