### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by zlamalp** [mkiol/GNotifier#64]
Hi, can you please fix Czech translation ? You have it as "cz" but it should be "cs" in order to be recognized by the Firefox / Thunderbird. Here is also updated translation which I use locally.

Thank you.

```
{
 "File": "Soubor", 
 "Folder": "Složka", 
 "New_message": "Nová zpráva!", 
 "New_message_from": "Nová zpráva od", 
 "Number_of_unread_messages": "Počet nepřečtených:", 
 "Open_file": "Otevřít soubor", 
 "Open_folder": "Otevřít složku", 
 "download_finished": "Stahování dokončeno", 
 "open": "Otevřít"
}
```

**Comment by mkiol** [comment]
Sure. Here is new [xpi package](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.1-pre1.xpi).

**Comment by zlamalp** [comment]
Hi, it works as expected. Thank you.
