### ISSUE TITLE
[not real issue but…] Signed or verified plugins ?

### ISSUE THREAD

**Issue by Coeur-Noir** [mkiol/GNotifier#68]
Firefox warns about Gnotifier not being signed or verified

https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

Might be a problem later…

**Comment by mkiol** [comment]
Right... Signed version is the version reviewed by Mozilla. Currently 1.8.9 is signed and available to download on [AMO](https://addons.mozilla.org/pl/firefox/addon/gnotifier/). New version (1.9.0) is waiting (for few months) in the review quee. So, hopefully it will be signed sooner or later.

**Comment by Coeur-Noir** [comment]
![capture du 2015-10-16 13 05 15](https://cloud.githubusercontent.com/assets/1895947/10540256/b5ac3c5a-7406-11e5-87bf-2863767eaa5b.png)
Thanx for your answer. So is the warning shown above "normal" ? Roughly it says : Gnotifier has not been verified for its use in Firefox.

**Comment by mkiol** [comment]
Something is wrong. Version "1.8.9.1-signed" is verified and signed. FF should not display warning message. Try to uninstall current version and install Gnotifier directly from https://addons.mozilla.org/pl/firefox/addon/gnotifier/.

**Comment by Coeur-Noir** [comment]
Hello,

Uninstall & re-install → you're right, no more warning !

Thanx a lot !

**Comment by neopostmodern** [comment]
Now, as of FF43, many users will run into this problem because unsigned extensions are now disabled by default and the upgrade path for this addon seams to somehow not automatically switch to the signed version.
Is there anything that could be done to fix this before everybody (or: many users) has to uninstall & install manually?

**Comment by mkiol** [comment]
> by default and the upgrade path for this addon seams to somehow not automatically switch to the signed version

Honestly, I've no idea why auto-upgrade thing doesn't work. I don't see anything I could do to resolve this. The only solution I found so far is reinstalling. 

> I uninstalled & reinstalled just now and issue persists; not signed

I can't reproduced your observation. I've tested it on both fresh and not-fresh Windows and Linux installation and 1.9.1 package downloaded from [AMO](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/ ) was always signed. I wonder if there is something specific in your setup which results in the problem?

**Comment by neopostmodern** [comment]
I just took a screenshot of the AMO site:
![gnotifier](https://cloud.githubusercontent.com/assets/786840/12050285/271c2054-aef3-11e5-8b8a-a30b603e43a9.png)
...and versions history:
![gnotifier-versions](https://cloud.githubusercontent.com/assets/786840/12050287/2a8554c2-aef3-11e5-8735-ef5acca9f867.png)

So: it seems that the `1.9.1` package offered to me for some reason is not signed.

*This is FF43 on Ubuntu 15.10*

**Comment by mkiol** [comment]
I think there has been some misunderstanding. So, "1.9.1" or "1.9.1-signed" is just a name and the lack of "-signed" doesn't indicate that package is not signed. When Mozilla introduced certificates for extension, all old XPI packages on AMO were auto signed and auto uploaded with new name ending with "-signed". But, now, every new XPI that pass AMO review process is signed by default, so there is no need to add anything to the name.

If your FF doesn't show warning message like below, everything is ok.
![capture du 2015-10-16 13 05 15](https://cloud.githubusercontent.com/assets/1895947/10540256/b5ac3c5a-7406-11e5-87bf-2863767eaa5b.png)

**Comment by neopostmodern** [comment]
Thanks for the clarification. The thing is, it *does* show the warning:
![gnotifier-about](https://cloud.githubusercontent.com/assets/786840/12052218/ea103bf4-af0c-11e5-9288-423c165d96ac.png)

**Comment by mkiol** [comment]
I'm puzzled.. have no idea where could be a problem. Did you try test it with a fresh FF profile?

**Comment by neopostmodern** [comment]
Just did. Works perfectly fine then. Which leaves me puzzled too, guess my current profile's just cursed. Thanks anyway.
*If anybody stumbles across this who knows how to delete the cached verifications...*

**Comment by alexander255** [comment]
@neopostmodern 
Probably won't happen (did you try to delete/restart/install btw?)
You could also try to remove (MAKING A BACKUP) the `extensions.ini`, `extensions.json` and `extensions.sqlite` files from your profile directory (`~/.mozilla/firefox/<PROFILE NAME>`).

**Comment by neopostmodern** [comment]
@alexander255 - Looks like it worked! Thank you!
For anybody else, attempting above fix: you'll have to re-enable / re-install all your addons, but you'll be asked or just go to `about:addons` - it remembers you're collection.
