### ISSUE TITLE
[thunderbird] Add Icedove support

### ISSUE THREAD

**Issue by paretje** [mkiol/GNotifier#71]
Would it be possible to add support for Icedove? I just tested, and it works alright when I add tests for Icedove for the 1.9.1-pre3 xpi.

I tried editing the source code, but I couldn't create an xpi for it. For example, I didn't find the options.xul, or does it need to be generated? Anyway, the changes are quite trivial.

**Comment by mkiol** [comment]
Sure. Support for Icedove is added in 54508b9 commit. 

> I tried editing the source code, but I couldn't create an xpi for it. For example, I didn't find the options.xul, or does it need to be generated?

Yes, `options.xul` and other files form XPI is generated. I am using [cfx](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx) tool from Add-on SDK to do that.

**Comment by paretje** [comment]
Thanks!
