### ISSUE TITLE
RSS Notifications Spam

### ISSUE THREAD

**Issue by roughnecks** [mkiol/GNotifier#77]
Hi there,
I just installed GNotifier on Thunderbird 38.4.0 (Windows 10) and it's working fine but I got this annoying issue with RSS: I am notified about each and every RSS article being fetched.

Is there a way/workaround to be notified on emails only?
Thanks

**Comment by mkiol** [comment]
Thank you for the report. So, Gnotifier generates notification on every new message in TB folder. Unfortunately, it can not be changed on the configuration level. Obviously, I forgot that not only emails can be in folder - also RSS items. I don't see any quick workaround, It needs to be solved in code. I'll try to figure something during weekend.

**Comment by mkiol** [comment]
Please check [this](https://github.com/mkiol/GNotifier/raw/master/gnotifier-1.9.2-pre2.xpi) xpi. There is new option to enable/disable notifications for RSS. The default value is Disabled.

**Comment by roughnecks** [comment]
Hey, thanks for updating it but I cannot check it now because my PC broke up; I'll be back here to comment as soon as I get it running.

Thanks

**Comment by roughnecks** [comment]
I think this will take much more time than I expected.. feel free to close this bug report if it bothers you (or if anyone else can confirm it's working).

Sorry

**Comment by roughnecks** [comment]
Hey there, I think it's working fine, thanks for updating it and sorry for the delay (I just got my rig running again :)

Happy New Year!
