### ISSUE TITLE
Notification not showing on Nightly 47 Linux

### ISSUE THREAD

**Issue by 89luca89** [mkiol/GNotifier#80]
I hear the sound of the arrived notification, but no popup appears.
Tested on 2 gmail accounts, whatsapp, telegram, messenger.
Download notification works as expected!

Can I help to debug in any way??

Thanks!

**Comment by mkiol** [comment]
Thanks for the report. I see this issue as well. I don't see any errors on console coming form Gnotifier, so it seems to be bug inside FF. Well, it is Nightly, so I don't expect everything to be working on this stage. My experience is that most of bugs are fixed in Beta release. 

I also noticed that native notifications are (finally) enabled without use of any extension. Maybe Gnotifier is not needed any more..

**Comment by 89luca89** [comment]
Well it seems it has notifications  similar to chrome, but they don't interact with the desktop notification center like gnotify does :-)

I will wait for the beta release and wait then!

**Comment by xdevla** [comment]
I've the same issue with FF 44.0

**Comment by mkiol** [comment]
@xdevla Would you please try to do tests on fresh FF profile? I'm using Gnotifier with FF44 without any problems so far...

**Comment by xdevla** [comment]
@mkiol my bad, the notify daemon wasn't running that's why I got the default notification as fallback

**Comment by mkiol** [comment]
@89luca89 It seams that new [1.9.5-pre2](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.5-pre2.xpi) package is compatible with FF 47. I would be grateful if you could try it and confirm.

**Comment by 89luca89** [comment]
Hi! It works on 47 and 48!
Thank you very much!

Out of curiosity (and topic) is it possible to compile the extension directly from source instead of the xpi delivered in the folder?

Thank you very much!

**Comment by mkiol** [comment]
> is it possible to compile the extension directly from source

To create XPI package, you need to install [jpm](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Installation) tool. After doing that, go to "source" directory and run ``jpm xpi``.

**Comment by 89luca89** [comment]
Thank you very much!
