### ISSUE TITLE
Linux | Plasmashell

### ISSUE THREAD

**Issue by christophschw** [mkiol/GNotifier#81]
Hey,
first let me say: really nice addon! Love to use it and it's very smooth. Thank you!

I'd like to know if there's a possibility to change the popup duration for Plasma respectively libnotify, I guess. The main reason is that Plasma doesn't have any notification history for common notifications anymore, ( https://github.com/blue-systems/plasma-5.4/issues/48 ) so it would be great to flag the popups whether as persistence or to rise the expire time. So I wouldn't miss any popups anymore.

It would be great to have an interface option to do this. But it would be also very good for me to alter the code which generates the behavior. The problem: I don't have a clue ;)

Thanks in advance!

**Comment by mkiol** [comment]
In the latest [package](https://github.com/mkiol/GNotifier/blob/master/xpi/gnotifier-1.9.2-pre4.xpi?raw=true), I've added option to define "Notification timeout". It works on Plasma5 - tested on OpenSUSE 42.1. 

Unfortunately, I wasn't able to set the notification to never expire. Actually, libnotify/D-Bus API has such option, but Plasma seams not to support it.

**Comment by christophschw** [comment]
Thank you! It seems very promising, but unfortunately the update breaks the whole functionality of your add-on...
Fedora 23 and FF 44, new configuration. What additional infos do you need? FF-Debug-Output?

If you set libnotify-timeout to 0, the notification will be saved at least in the notification history of plasma.

**Comment by mkiol** [comment]
Obviously it doesn't work at all. Sorry - my stupid mistake.

[Here](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.2-pre5.xpi) is new package. I added option to disable expiration. Seams to work great!

**Comment by christophschw** [comment]
Yeah, great, it works very well! Thank you :)

**Comment by christophschw** [comment]
Today was my first day working (at my job) with your addon and I have to say it is incredibly useful for me.
Thanks again for your great work!

**Comment by mkiol** [comment]
Glad I could help. If you come up with other useful ideas how to improve GNotifier, please let me know.
