### ISSUE TITLE
Addon Removed from the Mozilla Website

### ISSUE THREAD

**Issue by Meeplee** [mkiol/GNotifier#82]
Hello,

Just putting on a note mentioning the addon was removed from the mozilla addons website.
(https://addons.mozilla.org/firefox/addon/gnotifier/ no longer works)

Any feedback on this?

**Comment by mkiol** [comment]
Thanks. I'm aware of it. It is just my stupidity. I accidentally and unintentionally removed add-on from AMO. Now I have to resubmit it and wait once again for preliminary review...

**Comment by lavacano201014** [comment]
Fortunately, Mozilla currently allows you to disable signature checking in about:config (xpinstall.signatures.required). I think they intend to remove this in a future version, but for now, we don't have to wait for review.

**Comment by mkiol** [comment]
Keeping you informed - new and signed version (1.9.3) is now available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/gnotifier/).
