### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by roughnecks** [mkiol/GNotifier#84]
Hi there.

It's been a day now that Desktop notifications are gone; I'm only getting the white window on Thunderbird.

Recently I "messed up" a bit with the Config Editor to add a "X-Face" Header to my USENET account, but that's all I can think about. Are there some settings to check to try and fix it?

I've also upgraded to the latest GNotifier version right now and Thunderbird also got an upgrade minutes ago, but the issue was here before these changes occurred.

Thanks

**Comment by mkiol** [comment]
Thanks for the report. Would you please give me more details like OS, TB version, GN version ect.? If you are on Linux, do you see any error messages when running TB from command line?

**Comment by roughnecks** [comment]
My bad, sorry.

I'm running Windows 10 Home x64, Thunderbird 38.6.0 and GNotifier 1.9.3.

**Comment by vovkkk** [comment]
Same issue with Fx44 on Windows 8.1 Enterprise x32.

**Comment by mkiol** [comment]
A thousand apologies. I didn't somehow include necessary DLLs into XPI. 

Here is new package: [gnotifier-1.9.4-final.xpi](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.4-final.xpi).

**Comment by roughnecks** [comment]
Working just fine now, thank you.

Not sure if I have to close the report or wait for "vovkkk".

**Comment by vovkkk** [comment]
Yep, it works now. Thank you
