### ISSUE TITLE
[thunderbird] Notifications sent for every unread email

### ISSUE THREAD

**Issue by anidev** [mkiol/GNotifier#86]
Hi,

I've been having an issue with GNotifier on Linux where it displays a notification for every single unread email in my inbox whenever I receive a new email. So for example if I receive an email and already have 20 unread emails, I get 21 notifications. Then if I receive another email (and don't read any of the previous 21 emails), I get 22 notifications. I remember this used to work correctly (notification only for newly received emails), but sometime last year this unusual behavior started. I think I must have disabled the extension and forgotten about the issue until recently, when I enabled the extension and again saw the same issue. I can't say for sure exactly when the problem started, but I know it used to work properly before.

I'm running Thunderbird 38.5.0 on KDE 4.14, with GNotifier version 1.9.3. Let me know if there is any additional information I need to provide.

Thanks

**Comment by mkiol** [comment]
Thank you for letting me know. I'm aware of this behavior. 

To be precisely, notification is not for every unread email but for every message with "new" flag. New flag is visualized with yellow asterisk, like this:
![pp03](https://cloud.githubusercontent.com/assets/1420902/13124683/dda11560-d5c1-11e5-87d8-3a2047d5d424.png)
Previous behavior was to show notification only for latest "new" message. Probably both approaches are not excellent.

I promise to rethink this and propose something more suitable.

**Comment by anidev** [comment]
Thanks for looking into this problem.

I'm not 100% sure, but I think it still shows a notification even for messages that don't have the "new" flag. I just received 15 notifications, which is strange because I have 17 unread emails, only 3 of which have that "new" flag next to it. Could this be a bug with Thunderbird? It's hard to reproduce since sometimes I don't get a notification when I send a test email to myself.

**Comment by cgraeff** [comment]
I don't know if it is related to this issue, but I get notifications for messages in the spam folder too. I think this is not optimal, as this folder gets a lot of new messages and whenever the notifications start, I must wait for them to be displayed to be able to use the computer again (it's not that long, but it's not optimal).

**Comment by mkiol** [comment]
@cgraeff It is definitely a bug. New messages in Trash or Spam folder should not trigger notifications.

**Comment by mkiol** [comment]
I would be grateful if you could try the latest package [1.9.5-pre2](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.5-pre2.xpi). I did some improvements in the mechanism how new emails are detected.

**Comment by cgraeff** [comment]
Ok, I will use it for a while and then report if it fixed the behavior 
or not.

Thanks!

**Comment by mkiol** [comment]
I wonder if I could close this issue. @cgraeff @anidev Did you managed to check latest 1.9.5 package? Thanks for your help!

**Comment by cgraeff** [comment]
Sorry for the delay.

I have not seen any notifications with new messagens on spam folder, but 
I've seen a notification for a new message in the drafts folder.

**Comment by anidev** [comment]
The new behavior is better, but I think the problem is still there, though it doesn't always happen. Sometimes I will get just one notification for a new email, but then the next new email will trigger notifications for all the previous ones that are still marked as "new". It's hard to explain, I'll observe some more and try to get a better explanation. (Maybe it could be notifying for messages in Inbox as well as All Mail/Archives? Not sure)

**Comment by mkiol** [comment]
@cgraeff 
> drafts folder

You are right. I forgot to exclude also Draft & Archive folders...

**Comment by torinaki** [comment]
Same problem was on Windows 10 with Thunderbird on first run. All new notification was fine. I'm using version 1.9.6

**Comment by mkiol** [comment]
It is already fixed in 1.9.7.

**Comment by msoutopico** [comment]
I am getting this issue (notifications for old unread messages) in Thunderbird 68.4.2 for Windows 10 64bits.

**Comment by berchca** [comment]
I've always had this problem. I honestly just thought it was a feature that I didn't like: I keep a lot of unread email in my inbox, to track what needs to be handled, so every time I get a new message, 1/4 of my screen is covered by the "notification" that in fact doesn't show my any useful information (because it shows _too_ much information). 

Even a preference/option to limit the notification to only the message(s) that actually did just arrive would go a long way toward making Thunderbird usable for me.

Running Thunderbird version 68.8.0 on Windows.

Thank you for hearing me out.
