### ISSUE TITLE
Does not work in Windows 10

### ISSUE THREAD

**Issue by rcmero** [mkiol/GNotifier#91]
I have Firefox installed with GNotifier on several systems running Windows 8.1 and Windows 10. This morning when I accessed Windows 8.1 GNotifier works fine and I got the notifications I was expecting--from Download Manager and Feedly Notifier (default settings on both). Right now I'm on Windows 10 and I am not getting any notification from either of these.

Currently running Firefox 44, I believe there is an issue in recent versions in regards to notifications (#87).

**Comment by mkiol** [comment]
Thanks for the report. I was testing Gnotifier with FF 44 and with the latest one FF 45. In both cases everything seems to work fine. 

There is an issue in FF 46 (#87). The fix for that is in new [1.9.5-pre1](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.5-pre1.xpi) package.

**Comment by mkiol** [comment]
Is the issue still exists when you are using 1.9.5 package?

**Comment by rcmero** [comment]
I believe it’s working now last I checked. I’m on Windows 7 at the moment, so I can only test it next Tuesday.

**Comment by rcmero** [comment]
I tested it today and the notifications work now--I got the notification to update Firefox.

**Comment by mkiol** [comment]
Super! So, I am closing the issue.
