### ISSUE TITLE
Notifications doesn't work.. FF beta 46.0b1

### ISSUE THREAD

**Issue by Limdel** [mkiol/GNotifier#93]
Linux. I was using nightly, and moved to beta when notifications stopped working. now, after today's update, same happened to mah beta. HALP PLZ. T_T

**Comment by mkiol** [comment]
Thanks for the info. I've managed to track down the source of the problem. One of FF API (``nsIAlertsService``) was changed in 46. The fix is ready. Please check [1.9.5-pre1](https://github.com/mkiol/GNotifier/raw/master/xpi/gnotifier-1.9.5-pre1.xpi) package and let me know if it works.

**Comment by Limdel** [comment]
yes, it works. many thx. waiting for official update.

**Comment by Limdel** [comment]
back on aurora, and it work here too. just letting know.

**Comment by mkiol** [comment]
Great! So, I can close #80 :-)
