### ISSUE TITLE
Ability to define a user command for notifications

### ISSUE THREAD

**Issue by ix** [mkiol/GNotifier#94]
I don't use libnotify, instead I use a custom lemonbar-based notification system.

It would be nice if you could use a custom command.

**Comment by mkiol** [comment]
I have some doubts. Adding possibility to execute shell command could have an impact on FF security. Probably it could be an issue in the Mozilla review process... Nevertheless I want to give it a try. 

Could you please give me an example how to generate lemonbar notification?

**Comment by ix** [comment]
For me I just have a command "pop" echo a message to a FIFO, which lemonbar reads and outputs; the whole script is available [here](https://arcetera.moe/git/bin/file/notifyd.html).

**Comment by mkiol** [comment]
Please check the latest xpi [1.9.6-pre1](https://github.com/mkiol/GNotifier/tree/master/xpi). I've added "Notification engine" and "Custom command" options. If you like, you can pass some data to your script using %title, %text or %image strings.

**Comment by ix** [comment]
Thanks!

**Comment by mkiol** [comment]
OK, try new one - 1.9.6-pre2

> I just tested it, and Firefox's default notifications still show up.

That is strange. You should not see any other notifications...

> "pop" is in ~/bin/pop if that makes a difference, albeit it's in my PATH.

In the latest xpi, I've added PATH to command execution, so hopefully will work now. If it doesn't help, try to test it with following command: ``echo "%title">test.txt``

If you set the [extensions.sdk.console.logLevel to "all"](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/console), and run FF from command line, you should see command stdout and stderr.

**Comment by ix** [comment]
that option doesn't exist in about:config, and I still don't get anything, even with `echo "%title" > /home/arc/test`.

**Comment by mkiol** [comment]
Sorry for not mentioning it, but you need to create this option (right click on about:config, New->string... ). When you will be able to see stdout, please try command "set". I suspect that the problem is in the environment variables.

**Comment by grimpy** [comment]
Just tested this myself. I use this to give firefox urgent hit with following command

```
wmctrl -b add,demands_attention -r firefox
```

**Comment by mkiol** [comment]
@grimpy Cool! So, you can confirm that "custom command" option works, right?

**Comment by grimpy** [comment]
@mkiol yes `works for me` TM
