### ISSUE TITLE
[feature request] Thunderbird: ability to trigger notifications only for selected accounts, let user format notification's summary and body based on email properties

### ISSUE THREAD

**Issue by roomcays** [mkiol/GNotifier#97]
Hello and thank you for GNotifier - I have been using it with Thunderbird for a while and it plays nicely it's role.

I would welcome a feature that will filter some notifications out, particularly: based on email account a received message belongs to.
In minimal form this _could be_ achieved by presenting account's name in notification's summary or body. And this leads to another idea: to let user change what is sent to the notification (i.e. what email properties such as subject, sender, receiver, date, account, maybe stripped part of the body).

I know that this plugin is Firefox/Thunderbird so I am aware that adding features _"Thunderbird-only"_ may be out of the scope :)

**Comment by mkiol** [comment]
Thank you for finding Gnotifier useful :-)
> I would welcome a feature that will filter some notifications out, particularly: based on email account a received message belongs to.

Great idea. I'm adding it to the roadmap.

> presenting account's name in notification's summary or body. And this leads to another idea: to let user change what is sent to the notification (i.e. what email properties such as subject, sender, receiver, date, account, maybe stripped part of the body).

It is already possible. Thanks to @gabrielfin's super cool contribution done in #96, the [latest xpi package](https://github.com/mkiol/GNotifier/tree/master/xpi) has a new feature that enables you to define content of the notification. Possible options are: Subject, Sender (Name <E-mail>), Sender E-mail, Sender Name, Folder, Server, Size, Account, Body excerpt.

**Comment by roomcays** [comment]
Oh, thank you! I'm on my way to try the latest xpi package then. This might already partially solve my *problem* due to "Account" option availability (upon which I will then filter notifications, because I use [dunst](https://github.com/knopwob/dunst) and it is able to do some filtering).
Cheers!
